version: "3"

services:
  node:
    build: .
    container_name: secret_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    volumes: 
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: db
      PORT: ${PORT}
  db:
    container_name: secret_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password