version: "3"

services:
  node:
    build: .
    container_name: tekurt_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    volumes: 
      - ./:/app
    depends_on:
      - tekurt_dev_db
    ports:
      - 3000:3000
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      PORT: ${PORT}
  tekurt_dev_db:
    container_name: tekurt_dev_db
    depends_on:
      - tekurt_test_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
  tekurt_test_db:
    container_name: tekurt_test_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    command: mysqld --default-authentication-plugin=mysql_native_password